version: '3'
services:
  nginx:
    image: chipsofttech/nginx:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
    restart: always
  php:
    image: chipsofttech/php:latest
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
    restart: always
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
    restart: always 
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
